MicrosoftDocs/navdevitpro-content-pr

- dynamics-nav/api-reference/v1.0/dynamics_error_codes.md
> Fixed typo in Authentication_InvalidCredentials

- dynamics-nav/api-reference/v1.0/api/dynamics_salesquote_pdfdocument.md
Entitynames in plural and spelling correction of purchaseInvoices.
> SusanneWindfeldPedersen from OPS portal: Merge from master to live

- dynamics-nav/Deployment-Scenarios-for-the-Microsoft-Dynamics-NAV-Web-Server-Components.md
This PR updates the docs according to [defect 402837](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/402837).
[Deployment Scenarios for the Microsoft Dynamics NAV Web Server Components](https://review.docs.microsoft.com/en-us/dynamics-nav/deployment-scenarios-for-the-microsoft-dynamics-nav-web-server-components?branch=defect402837-aad-proxy)
> Update Deployment scenarios for AAD proxy

- dynamics-nav/deprecated-fields.md
**Global effort to fix broken links**
@edupont04
The Content & Learning team is fixing broken links on docs.microsoft.com for the rest of H2. This effort will eliminate potential accessibility, security, and usability issues. This PR includes only link fixes and does not change other content. Please review within five business days and merge, or comment in the PR with any changes you'd like to see. Thanks!
> [BrokenLinksH2] fixing broken link

- dynamics-nav/how-to-view-synchronization-job-queue-status.md
**Global effort to fix broken links**
@jswymer
The Content & Learning team is fixing broken links on docs.microsoft.com for the rest of H2. This effort will eliminate potential accessibility, security, and usability issues. This PR includes only link fixes and does not change other content. Please review within five business days and merge, or comment in the PR with any changes you'd like to see. Thanks!
> [BrokenLinksH2] fixing broken image

- dynamics-nav/Changes-to-Microsoft-Dynamics-NAV-Cmdlets-From-Previous-Release-2017.md
- dynamics-nav/Changes-to-Microsoft-Dynamics-NAV-Cmdlets-From-Previous-Release.md
> Validation: Removed Absolute Links

- dynamics-nav/How-to--Administer-Multiple-Microsoft-Dynamics-NAV-Server-Computers.md
> [BrokenLinksH2] Fix path in link

- dynamics-nav/Changes-to-Microsoft-Dynamics-NAV-Cmdlets-From-Previous-Release-2017.md
> [BrokenLinksH2] Fixed the link path

- dynamics-nav/APPLICATIONAREA-Function.md
- dynamics-nav/APPLICATIONPATH-Function.md
- dynamics-nav/ARRAYLEN-Function.md
- dynamics-nav/ASBOOLEAN-Function--TestPage-Field-.md
- dynamics-nav/ASCENDING-Function--TestPage-Filter-.md
- dynamics-nav/ASDECIMAL-Function--TestPage-Field-.md
- dynamics-nav/ASINTEGER-Function--TestPage-Field-.md
- dynamics-nav/ASSERTEQUALS-Function--TestPage-Field-.md
- dynamics-nav/ASSISTEDIT-Function--TestPage-Field-.md
- dynamics-nav/ATTACH-Function--Debugger-.md
- dynamics-nav/Accessing-Microsoft-Dynamics-NAV-Tables-with-External-Tools.md
- dynamics-nav/AltSearchField-Property.md
- dynamics-nav/Altering-Databases---Collation-Tab.md
- dynamics-nav/Altering-Databases---Database-Files-Tab.md
- dynamics-nav/Altering-Databases---General-Tab.md
- dynamics-nav/Altering-Databases---Integration-Tab.md
- dynamics-nav/Altering-Databases---Options-Tab.md
- dynamics-nav/Altering-Databases---Transaction-Log-Files-Tab.md
- dynamics-nav/Application-Design-Overview.md
- dynamics-nav/Application-Test-Automation.md
- dynamics-nav/ApplicationArea-Property.md
- dynamics-nav/Arithmetic-Operators.md
- dynamics-nav/Arranging-Fields-in-Rows-and-Columns-Using-a-FixedLayout-Control.md
- dynamics-nav/Arranging-Fields-in-Rows-and-Columns.md
- dynamics-nav/Array-Functions.md
- dynamics-nav/AssistEdit-Property.md
- dynamics-nav/Asynchronous-Considerations.md
- dynamics-nav/Authenticating-Users-with-Active-Directory-Federation-Service.md
- dynamics-nav/AutoCalcField-Property.md
- dynamics-nav/AutoFormatExpr-Property.md
> [Bulk] Validation: validation fixes JM 5/24c

- dynamics-nav/Troubleshooting--401---Unauthorized--Access-is-denied-due-to-invalid-credentials.md
- dynamics-nav/Troubleshooting-saml-token-invalid-validity-period-ended.md
This PR fixes 4 issues (but only 2 fixes).
> [Bulk] Validation: Fix duplicate title and description

- dynamics-nav/SETVALUE-Function--TestPage-Field-.md
- dynamics-nav/SETVIEW-Function--Record-.md
- dynamics-nav/SETVIEW-Function--RecordRef-.md
- dynamics-nav/SETVIEW-Function.md
- dynamics-nav/SID-Function--Database-.md
- dynamics-nav/SIFT-and-Performance.md
- dynamics-nav/SIFT-and-SQL-Server.md
- dynamics-nav/SKIP-Function--Report--XMLport-.md
- dynamics-nav/SKIPSYSTEMTRIGGERS-Function--Debugger-.md
- dynamics-nav/SLEEP-Function.md
- dynamics-nav/Setting-.NET-Framework-Types-to-Target-the-Microsoft-Dynamics-NAV-Windows-Client-or-Server.md
- dynamics-nav/Setting-Database-Owner-and-Security-Administration-Permissions.md
- dynamics-nav/Setting-Up-Colored-Indicators-on-Cues-by-Using-Codeunit-1.md
- dynamics-nav/Setting-Up-Colored-Indicators-on-Cues.md
- dynamics-nav/Setting-Up-Cues.md
- dynamics-nav/Setting-Up-Dynamics-CRM-Integration.md
- dynamics-nav/Setting-Up-the-Home-Button-and-Home-Items.md
- dynamics-nav/Setting-up-Hyperlinks-in-Word-Report-Layouts.md
- dynamics-nav/Setting-up-Office-Add-Ins-Outlook-Inbox.md
- dynamics-nav/SetupComplete2.cmd-File-Example.md
- dynamics-nav/ShortCutKey-Property.md
- dynamics-nav/ShowAsTree-Property.md
- dynamics-nav/ShowCaption-Property.md
- dynamics-nav/ShowFilter-Property.md
- dynamics-nav/ShowMandatory-Property.md
- dynamics-nav/ShowPrintStatus-Property.md
- dynamics-nav/SignDisplacement-Property.md
- dynamics-nav/SingleInstance-Property.md
- dynamics-nav/Sizing-a-Control-Add-in-on-a-Page.md
This PR fixes 29 missing descriptions.
> [Bulk] Validation: fixed missing descriptions II 5/30

- dynamics-nav/SOAP-Web-Service-URIs.md
- dynamics-nav/SOAP-Web-Services.md
- dynamics-nav/SQL-Advanced-Options-for-Data-Item-Link-Types.md
- dynamics-nav/SQL-Server-Database-Components.md
- dynamics-nav/SQL-Server-Sysprep-Installation-Configuration-File-Example.md
- dynamics-nav/SQL-Timestamp-Property.md
- dynamics-nav/SQLIndex-Property.md
- dynamics-nav/SQLJoinType-Property.md
- dynamics-nav/STARTSESSION-Function--Sessions-.md
- dynamics-nav/STEPINTO-Function--Debugger-.md
- dynamics-nav/STEPOUT-Function--Debugger-.md
- dynamics-nav/STEPOVER-Function--Debugger-.md
- dynamics-nav/STOP-Function--Debugger-.md
- dynamics-nav/Sorting-Numeric-Values.md
- dynamics-nav/SourceExpr-Property.md
- dynamics-nav/SourceField-Property.md
- dynamics-nav/SourceTable-Property--XMLports-.md
- dynamics-nav/SourceTable-Property.md
- dynamics-nav/SourceTableTemporary-Property.md
- dynamics-nav/SourceTableView-Property--XMLports-.md
- dynamics-nav/SourceTableView-Property.md
- dynamics-nav/SourceType-Property.md
- dynamics-nav/Special-Permission-Sets.md
- dynamics-nav/Special-Tables.md
- dynamics-nav/Standard-Day-Time-Unit-Property.md
- dynamics-nav/Standard-and-User-Defined-Functions.md
- dynamics-nav/Statements-and-Expressions.md
- dynamics-nav/sql-server-query-hints.md
- dynamics-nav/starting-the-windows-client-at-the-command-prompt.md
This PR fixes 29 missing descriptions.
> [Bulk] Validation: Fixed missing descriptions III 5/30

- dynamics-nav/STOPSESSION-Function--Sessions-.md
- dynamics-nav/STRLEN-Function--Code--Text-.md
- dynamics-nav/STRMENU-Function--Dialog-.md
- dynamics-nav/STRMENU-Function.md
- dynamics-nav/STRSUBSTNO-Function--Code--Text-.md
- dynamics-nav/String-Functions.md
- dynamics-nav/Strings.md
- dynamics-nav/StyleExpr-Property.md
- dynamics-nav/SubPageLink-Property.md
- dynamics-nav/SubPageView-Property.md
This PR fixes 10 missing descriptions.
> [Bulk] Validation: Fixed missing descriptions IV 5/30

- dynamics-nav/LENGTH-Function--BigText-.md
- dynamics-nav/LENGTH-Function--FieldRef-.md
- dynamics-nav/LOCKTABLE-Function--Record-.md
- dynamics-nav/LOCKTABLE-Function.md
- dynamics-nav/LOCKTIMEOUT-Function--Database-.md
- dynamics-nav/LOOKUP-Function--TestPage-Field-.md
- dynamics-nav/LOWERCASE-Function--Code--Text-.md
- dynamics-nav/LinkFields-Property.md
- dynamics-nav/LinkTable-Property.md
- dynamics-nav/LinkTableForceInsert-Property.md
- dynamics-nav/LinkedInTransaction-Property.md
- dynamics-nav/LinkedObject-Property.md
- dynamics-nav/Linking-to-the-Microsoft-Dynamics-NAV-Universal-App.md
- dynamics-nav/LinksAllowed-Property.md
- dynamics-nav/Local-Property.md
- dynamics-nav/Locking-and-Unlocking-Objects.md
- dynamics-nav/Login-Stored-Procedure.md
- dynamics-nav/Lookup-Property.md
- dynamics-nav/LookupPageID-Property.md
- dynamics-nav/MaintainSIFTIndex-Property.md
- dynamics-nav/MaintainSQLIndex-Property.md
- dynamics-nav/Maintaining-Table-Relationships-on-SQL-Server.md
- dynamics-nav/Making-a-Page-or-Report-Available-From-Search-in-the-Windows-Client.md
- dynamics-nav/Managing-Encryption-Keys-for-SQL-Server-Authentication.md
- dynamics-nav/Managing-Language--Regional-Settings--and-Time-Zone-in-the-Microsoft-Dynamics-NAV-Web-Client.md
- dynamics-nav/Managing-Permissions-and-Permission-Sets.md
- dynamics-nav/Managing-Time-Zones-with-Web-Services.md
- dynamics-nav/loadpackagedata-function.md
- dynamics-nav/localeid-function-sessionsettings.md
- dynamics-nav/manage-data-encryption.md
> [Bulk] Validation: validation fixes 5/27b

- dynamics-nav/MODIFY-Function--RecordRef-.md
- dynamics-nav/MODIFYALL-Function--Record-.md
- dynamics-nav/MinOccurs-Property.md
- dynamics-nav/MinValue-Property.md
- dynamics-nav/ModifyAllowed-Property.md
- dynamics-nav/Modifying--Uninstalling--or-Repairing-Microsoft-Dynamics-NAV.md
- dynamics-nav/Monitoring-Database-Deadlocks.md
- dynamics-nav/Numeric-Functions.md
- dynamics-nav/Numeric-Property.md
- dynamics-nav/OBJECTID-Function--Page-.md
- dynamics-nav/OData-Web-Services.md
- dynamics-nav/Object-Level-Security.md
- dynamics-nav/Object-Specifications-and-Limitations.md
- dynamics-nav/Objects.md
- dynamics-nav/Occurrence-Property.md
- dynamics-nav/OnAction-Trigger.md
- dynamics-nav/OnAfterAssignField-Trigger.md
- dynamics-nav/OnAfterAssignVariable-Trigger.md
- dynamics-nav/OnAfterGetCurrRecord-Trigger.md
- dynamics-nav/OnAfterGetField-Trigger.md
- dynamics-nav/OnAfterGetRecord--Data-Items--Trigger.md
- dynamics-nav/OnAfterGetRecord--XMLports--Trigger.md
- dynamics-nav/OnAfterGetRecord-Trigger.md
- dynamics-nav/OnAfterInitRecord-Trigger.md
- dynamics-nav/OnAfterInsertRecord-Trigger.md
- dynamics-nav/OnAfterModifyRecord-Trigger.md
- dynamics-nav/OnAssistEdit-Trigger.md
one file with a links issue included
> Validation: descriptions 

- dynamics-nav/HYPERLINK-Function.md
- dynamics-nav/How-to--Use-Streams-to-Write-to-Text-Files.md
- dynamics-nav/How-to--Use-SystemService-to-Find-Companies.md
- dynamics-nav/How-to--Verify-the-Paper-Size.md
- dynamics-nav/How-to--View-All-Table-Fields-for-a-Record.md
- dynamics-nav/How-to--View-Names-and-Captions.md
- dynamics-nav/How-to--View-Performance-Counter-Data-for-a-Data-Collector-Set.md
- dynamics-nav/How-to--View-Variables-That-Are-in-Scope.md
- dynamics-nav/How-to--View-and-Export-the-Dataset-for-a-Report.md
- dynamics-nav/How-to--View-and-Sort-Table-Data.md
- dynamics-nav/How-to--View-or-Modify-Properties-on-a-Key.md
- dynamics-nav/How-to--View-or-Modify-Properties-on-a-Table-or-Field.md
- dynamics-nav/How-to--View-the-Event-Subscriptions.md
- dynamics-nav/How-to-view-dynamics-crm-connection-status.md
- dynamics-nav/ID-Property.md
- dynamics-nav/IMPORT-Function--BLOB-.md
- dynamics-nav/IMPORT-Function--XMLport-.md
- dynamics-nav/IMPORTDATA-Function--Database-.md
- dynamics-nav/IMPORTENCRYPTIONKEY.md
- dynamics-nav/IMPORTFILE-Function--Media-.md
- dynamics-nav/IMPORTFILE-Function--MediaSet-.md
- dynamics-nav/IMPORTSTREAM-Function--Media-.md
- dynamics-nav/Image-Property--Fields-.md
- dynamics-nav/Image-Property.md
- dynamics-nav/ImportLangModule.md
- dynamics-nav/ImportObjects.md
- dynamics-nav/Importance-Property.md
- dynamics-nav/Importing-and-Exporting-Objects.md
- dynamics-nav/how-to-work-with-the-basic-permission-set.md
- dynamics-nav/implementation-tips-gestures-property.md
> [Bulk] Validation: validation fixes 5/26e

- dynamics-nav/How-to--Skip-Codeunit-1.md
- dynamics-nav/How-to--Sort-a-Query-Dataset-in-Ascending-or-Descending-Order.md
- dynamics-nav/How-to--Specify-Printer-Selection-for-Reports.md
- dynamics-nav/How-to--Specify-Rounding-Precision.md
- dynamics-nav/How-to--Specify-When-UI-Elements-Are-Removed.md
- dynamics-nav/How-to--Specify-the-Start-ID-Offset-of-Elements-on-Objects.md
- dynamics-nav/How-to--Start--Stop--Restart--or-Remove-a-Microsoft-Dynamics-NAV-Server-Instance.md
- dynamics-nav/How-to--Start-SQL-Browser-Service.md
- dynamics-nav/How-to--Style-Field-Text-on-a-Page.md
- dynamics-nav/How-to--Subscribe-to-Events-in-a-.NET-Framework-Type.md
- dynamics-nav/How-to--Synchronize-Table-and-SQL-Server-Relationships.md
- dynamics-nav/How-to--Synchronize-the-Tenant-Database-with-the-Application-Database.md
- dynamics-nav/How-to--Test-the-ADCS-Connection.md
- dynamics-nav/How-to--Try-Out-the-UI-Elements-Removal-Feature-Based-on-Demonstration-Permission-Sets.md
- dynamics-nav/How-to--Uninstall-Language-Modules.md
- dynamics-nav/How-to--Unlock-an-Object.md
- dynamics-nav/How-to--Upload-the-License-File.md
- dynamics-nav/How-to--Use-Event-Viewer-to-Collect-and-View-Trace-Events.md
- dynamics-nav/How-to--Use-FlowFilters-in-OData-URIs.md
- dynamics-nav/How-to--Use-Logman-to-Collect-Event-Trace-Data.md
- dynamics-nav/How-to--Use-OData-to-Return-Obtain-a-JSON-Document.md
- dynamics-nav/How-to--Use-OData-to-Return-Obtain-a-Service-Metadata--EDMX--Document.md
- dynamics-nav/How-to--Use-OData-to-Return-Obtain-an-AtomPub-Document.md
- dynamics-nav/How-to--Use-Option-Strings-in-Multilanguage-Implementations.md
- dynamics-nav/How-to--Use-PerfView-to-Collect-Event-Trace-Data.md
- dynamics-nav/How-to--Use-PerfView-to-View-Event-Trace-Data.md
- dynamics-nav/How-to--Use-Performance-Monitor-to-Collect-Event-Trace-Data.md
- dynamics-nav/How-to--Use-Streams-to-Read-from-Text-Files.md
- dynamics-nav/How-to--Use-a-Timestamp-Field.md
- dynamics-nav/How-to--Use-an-Access-Key-for-SOAP-and-OData-Web-Service-Authentication.md
> [Bulk] Validation: validation fixes JM 5/26d

- dynamics-nav/How-to--Export--Edit--and-Import-Translated-Profile-Strings.md
- dynamics-nav/How-to--Export-Objects.md
- dynamics-nav/How-to--Export-Your-Solution-to-a-Database-Backup-File.md
- dynamics-nav/How-to--Export-and-Import-Companies-and-Other-Data-using-Windows-PowerShell-Cmdlets.md
- dynamics-nav/How-to--Export-the-Application-Tables-to-a-Dedicated-Database.md
- dynamics-nav/How-to--Format-Date-Values.md
- dynamics-nav/How-to--Format-Decimal-Values.md
- dynamics-nav/How-to--Get-the-Microsoft-Azure-Image-Name.md
- dynamics-nav/How-to--Implement-Location-in-C-AL.md
- dynamics-nav/How-to--Implement-the-Camera-in-C-AL.md
- dynamics-nav/How-to--Import-Export-Permission-Sets-Permissions.md
- dynamics-nav/How-to--Import-Objects.md
- dynamics-nav/How-to--Import-and-Export-a-Word-Report-Layout.md
- dynamics-nav/How-to--Include-Microsoft-Dynamics-Online-Connect-on-Role-Centers.md
- dynamics-nav/How-to--Increase-the-Size-of-Database-Files.md
- dynamics-nav/How-to--Increase-the-Size-of-Transaction-Log-Files.md
- dynamics-nav/How-to--Insert-Items-in-a-MenuSuite.md
- dynamics-nav/How-to--Install-C-SIDE-Development-Environment.md
- dynamics-nav/How-to--Install-Control-Add-Ins-and-Support-Files-for-Your-Solution.md
- dynamics-nav/How-to--Install-Language-Modules.md
- dynamics-nav/How-to--Install-a-Windows-Client-Control-Add-in-Assembly.md
- dynamics-nav/How-to--Install-and-Configure-Internet-Information-Services-for-Microsoft-Dynamics-NAV-Web-Client.md
- dynamics-nav/how-to-export-and-import-encryption-keys.md
This PR fixes 23 missing descriptions.
> [Bulk] Validation: validation fixes JM 5/26c

- dynamics-nav/HASFILTER-Function--Record-.md
- dynamics-nav/HASFILTER-Function--RecordRef-.md
- dynamics-nav/HASLINKS-Function--Record-.md
- dynamics-nav/HASLINKS-Function--RecordRef-.md
- dynamics-nav/HASTABLECONNECTION-Function--Database-.md
- dynamics-nav/HASVALUE-Function--BLOB-.md
- dynamics-nav/HASVALUE-Function--Media-.md
- dynamics-nav/Handling-UI-Interaction-When-Working-with-Web-Services.md
- dynamics-nav/HasCustomLayout-Function.md
- dynamics-nav/Help-Table-of-Contents.md
- dynamics-nav/HideValue-Property.md
- dynamics-nav/Hiding-User-Interface-Elements-Based-on-Application-Area.md
- dynamics-nav/How-to--Add-a-Global-Variable-to-a-Codeunit.md
- dynamics-nav/How-to--Create-a-Codeunit.md
- dynamics-nav/How-to--Create-a-Data-Collector-for-Microsoft-Dynamics-NAV-Performance-Counters.md
- dynamics-nav/How-to--Define-Promoted-Action-Categories-Captions-for-the-Ribbon.md
- dynamics-nav/How-to--Delete-Databases.md
- dynamics-nav/How-to--Delete-Translated-Strings.md
- dynamics-nav/How-to--Deploy-Microsoft-Dynamics-NAV-on-Microsoft-Azure-by-Using-the-Example-Scripts.md
- dynamics-nav/How-to--Deploy-a-Microsoft-Dynamics-NAV-Database-to-Azure-SQL-Database.md
- dynamics-nav/How-to--Determine-the-Public-Key-Token-of-the-Windows-Client-Control-Add-in-and-.NET-Framework-Assembly.md
- dynamics-nav/How-to--Disable-Debugging.md
- dynamics-nav/How-to--Disable-Logging-Events-to-the-Windows-Application-Log.md
- dynamics-nav/How-to--Display-Data-as-Bricks.md
- dynamics-nav/How-to--Download-and-Import-Publish-Settings-and-Subscription-Information.md
- dynamics-nav/How-to--Enable-Web-Services-for-ADCS.md
- dynamics-nav/How-to--Enter-Text-in-the-Multilanguage-Editor.md
- dynamics-nav/How-to--Export-and-Import-Companies-and-Other-Data-in-Clients.md
- dynamics-nav/how-to-enable-and-disable-encryption-keys.md
- dynamics-nav/how-to-enable-default-dynamics-crm-synchronization-setup.md
> [Bulk] Validation: validation fixes JM 5/26b

- dynamics-nav/GETRANGEMIN-Function--FieldRef-.md
- dynamics-nav/GETRECORD-Function--RecordID-.md
- dynamics-nav/GETSTAMP-Function--File-.md
- dynamics-nav/GETTABLE-Function--RecordRef-.md
- dynamics-nav/GETURL-Function.md
- dynamics-nav/GETVALIDATIONERROR-Function--TestPage--TestPage-Field-.md
- dynamics-nav/GETVIEW-Function--Record-.md
- dynamics-nav/GETVIEW-Function--RecordRef-.md
- dynamics-nav/GETVIEW-function--FilterPageBuilder-.md
- dynamics-nav/GLOBALLANGUAGE-Function.md
- dynamics-nav/GOTOKEY-Function--TestPage-.md
- dynamics-nav/GOTORECORD-Function--TestPage-.md
- dynamics-nav/GUIALLOWED-Function.md
- dynamics-nav/GetRecIdFromKey.md
- dynamics-nav/Getting-Started-Developing-for-the-Microsoft-Dynamics-NAV-Universal-App.md
- dynamics-nav/Getting-Started.md
- dynamics-nav/GlobalVarAccess-Property.md
- dynamics-nav/Granules-Available-in-the-General-Ledger.md
- dynamics-nav/GroupType-Property.md
- dynamics-nav/HandlerFunctions-Property.md
- dynamics-nav/Handling-Errors-by-Using-Try-Functions.md
- dynamics-nav/Handling-Events-with-Microsoft-.NET-Framework-Interoperability.md
- dynamics-nav/Handling-Merge-Conflicts.md
- dynamics-nav/Handling-Missing-Option-Values-in-Mapping.md
This PR fixes 37 issues, missing descriptions and duplicate alt text.
> [Bulk] Validation: validation fixes JM 5/26a

- dynamics-nav/DMY2DATE-Function--Date-.md
- dynamics-nav/DOWNLOAD-Function--File-.md
- dynamics-nav/DOWNLOADFROMSTREAM-Function--File-.md
- dynamics-nav/DRILLDOWN-Function--TestPage-Field-.md
- dynamics-nav/DesignObject.md
- dynamics-nav/Designing-Word-Report-Layouts.md
- dynamics-nav/Designing-XMLports.md
- dynamics-nav/Developer-Option.md
- dynamics-nav/Developing-Multilanguage-Enabled-Applications.md
- dynamics-nav/Developing-Windows-Client-Control-Add-ins.md
- dynamics-nav/Developing-and-Installing-a-Microsoft-Dynamics-NAV-Apps-for-SharePoint.md
- dynamics-nav/Developing-for-the-Microsoft-Dynamics-NAV-Universal-App.md
- dynamics-nav/Developing-for-the-Microsoft-Dynamics-NAV-Web-Client.md
- dynamics-nav/Development-Environment--C-SIDE-.md
- dynamics-nav/Development-Environment-Commands.md
- dynamics-nav/Differences-and-Limitations-When-Developing-Pages-for-the-Microsoft-Dynamics-NAV-Universal-App.md
- dynamics-nav/Dimensions-Property.md
- dynamics-nav/Direction-Property.md
- dynamics-nav/Disable-Limit-Telemetry-Events.md
- dynamics-nav/Displaying-Charts-Using-the-Chart-Control-Add-in.md
- dynamics-nav/Dividing-the-Database-into-Companies.md
- dynamics-nav/DrillDown-Property.md
- dynamics-nav/DrillDownPageID-Property.md
- dynamics-nav/developer/api/xmldocumenttype-asxmlnode-method.md
- dynamics-nav/developer/api/xmlelement-selectnodes-xpath-nodelist-method.md
- dynamics-nav/developer/datatypes/Not supported/devenv-automation-data-type.md
- dynamics-nav/developer/datatypes/Not supported/devenv-ocx-data-type.md
- dynamics-nav/developer/devenv-next-steps.md
- dynamics-nav/developer/methods/devenv-export-method-xmlport.md
- dynamics-nav/displayname-function.md
> [Bulk] Validation: validation fixes JM 5/26

- dynamics-nav/uiref/-$-S_2148-Column-Filter-$-.md
- dynamics-nav/uiref/-$-S_2149-Order-By-$-.md
- dynamics-nav/uiref/-$-S_2150-Control-Add-ins-$-.md
- dynamics-nav/uiref/-$-S_2151-Namespaces-$-.md
- dynamics-nav/uiref/-$-S_2155-Chart-List-$-.md
- dynamics-nav/uiref/-$-S_2162-Error-List-$-.md
- dynamics-nav/uiref/-$-S_2170-Image-List-$-.md
- dynamics-nav/uiref/-$-S_2180-Access-By-Permission-$-.md
- dynamics-nav/uiref/-$-S_2181-Start-Data-Upgrade-$-.md
- dynamics-nav/uiref/-$-S_2182-Resume-Data-Upgrade-$-.md
- dynamics-nav/uiref/-$-S_22401-Query-Designer-$-.md
- dynamics-nav/uiref/-$-S_2335-Open-Database-$-.md
- dynamics-nav/uiref/-$-S_2338-New-Database-$-.md
- dynamics-nav/uiref/-$-S_2339-Alter-Database-$-.md
- dynamics-nav/uiref/-$-S_2341-Available-Microsoft-SQL-Servers-$-.md
- dynamics-nav/uiref/-$-S_2342-Available-Databases-$-.md
- dynamics-nav/uiref/-$-S_2345-Select-Server-$-.md
- dynamics-nav/uiref/-$-S_2347-Available-Server-Instances-$-.md
- dynamics-nav/uiref/-$-S_2349-Database-Information-$-.md
- dynamics-nav/uiref/-$-S_2354-License-Information-$-.md
- dynamics-nav/uiref/-$-S_2355-Options-$-.md
- dynamics-nav/uiref/-$-S_2356-Application-Languages-$-.md
- dynamics-nav/uiref/-$-S_2401-Navigation-Pane-Designer-$-.md
- dynamics-nav/uiref/-$-S_2410-Create-Item-$-.md
- dynamics-nav/uiref/-$-S_2420-Create-Menu-$-.md
- dynamics-nav/uiref/-$-S_2450-Show-Menus-$-.md
- dynamics-nav/uiref/-$-S_2460-Insert-Items-$-.md
- dynamics-nav/uiref/-$-S_2490-Menu-Properties-$-.md
- dynamics-nav/uiref/-$-S_2510-Group-Properties-$-.md
- dynamics-nav/uiref/-$-S_2600-Indent-Controls-$-.md
> [Bulk] Validation: fix missing descriptions II 5/26

- dynamics-nav/uiref/-$-S_11005-FlowFilter-$-.md
- dynamics-nav/uiref/-$-S_11006-Sort-$-.md
- dynamics-nav/uiref/-$-S_11120-New-Page-$-.md
- dynamics-nav/uiref/-$-S_11150-Page-Designer-Wizard--Available-Fields-$-.md
- dynamics-nav/uiref/-$-S_11162-Page-Designer-Wizard--FastTab-$-.md
- dynamics-nav/uiref/-$-S_11170-Page-Designer-Wizard--FactBox-$-.md
- dynamics-nav/uiref/-$-S_2051-Object-Designer-$-.md
- dynamics-nav/uiref/-$-S_2082-Language-Module-Export-$-.md
- dynamics-nav/uiref/-$-S_2091-About-$-.md
- dynamics-nav/uiref/-$-S_2092-Toolbar-$-.md
- dynamics-nav/uiref/-$-S_2093-Custom-Controls-$-.md
- dynamics-nav/uiref/-$-S_21001-XMLport-Designer-$-.md
- dynamics-nav/uiref/-$-S_21009-Table-List-$-.md
- dynamics-nav/uiref/-$-S_2101-Column-List---Table-$-.md
- dynamics-nav/uiref/-$-S_21010-Field-Lookup-$-.md
- dynamics-nav/uiref/-$-S_2102-Table-Designer-$-.md
- dynamics-nav/uiref/-$-S_2103-Keys-$-.md
- dynamics-nav/uiref/-$-S_2104-Field-Groups-$-.md
- dynamics-nav/uiref/-$-S_2121-Object-List-$-.md
- dynamics-nav/uiref/-$-S_2122-Field-List-$-.md
- dynamics-nav/uiref/-$-S_2123-Key-List-$-.md
- dynamics-nav/uiref/-$-S_2128-Windows-Language-List-$-.md
- dynamics-nav/uiref/-$-S_2134-Table-Relation-$-.md
- dynamics-nav/uiref/-$-S_2135-Table-View-$-.md
- dynamics-nav/uiref/-$-S_2136-Permissions-$-.md
- dynamics-nav/uiref/-$-S_2138-DataItem-Link-$-.md
- dynamics-nav/uiref/-$-S_21401-Page-Designer-$-.md
- dynamics-nav/uiref/-$-S_21407-Action-Designer-$-.md
- dynamics-nav/uiref/-$-S_21408-Page-Preview-$-.md
- dynamics-nav/uiref/-$-S_2141-Multilanguage-Editor-$-.md
> [Bulk] Validation: Fixed missing descriptions 5/26

- dynamics-nav/TRUNC-Function--File-.md
- dynamics-nav/TYPE-Function--FieldRef-.md
- dynamics-nav/Troubleshooting---You-cannot-enter-table--Table-Name--in-TableNo--error-when-compling-an-object.md
- dynamics-nav/Troubleshooting--Running-the-Cmdlet-in-a-Multitenant-Microsoft-Dynamics-NAV-Environment.md
- dynamics-nav/Troubleshooting--SAML2-token-not-valid-because-validity-period-ended.md
- dynamics-nav/Troubleshooting--SQL-Server-Connection-Problems.md
- dynamics-nav/Troubleshooting--Server-Error-in-----Application.-Access-Denied.md
- dynamics-nav/Troubleshooting--The-Server-Is-Not-Compatible.md
- dynamics-nav/Troubleshooting--Visual-Studio-Report-Designer-provided-metadata-is-not-valid.md
- dynamics-nav/Troubleshooting-tenant is not accessible.md
- dynamics-nav/Troubleshooting-the-Microsoft-Dynamics-NAV-Universal-App.md
- dynamics-nav/Troubleshooting-web-client-errors-application-request-routing.md
- dynamics-nav/TryFunction-Property.md
- dynamics-nav/Tuning-and-Tracing.md
- dynamics-nav/Type-Conversion-Rules-for-Arithmetic-Operators.md
- dynamics-nav/Type-Conversion-in-Expressions.md
- dynamics-nav/Type-Conversion.md
- dynamics-nav/Types-of-Reports.md
- dynamics-nav/ui-how-enter-date-time.md
- dynamics-nav/uiref/-$-N_534_4-Name-$-.md
- dynamics-nav/uiref/-$-N_9510-Event-Subscriptions-$-.md
- dynamics-nav/uiref/-$-N_9990-Code-Coverage-$-.md
- dynamics-nav/uiref/-$-S_10203_30-C-AL-Editor-$-.md
- dynamics-nav/uiref/-$-S_10204-C-AL-Globals-$-.md
- dynamics-nav/uiref/-$-S_10205-C-AL-Locals-$-.md
- dynamics-nav/uiref/-$-S_10209-C-AL-Symbol-Menu-$-.md
- dynamics-nav/uiref/-$-S_11001-Find-$-.md
- dynamics-nav/uiref/-$-S_11002-Replace-$-.md
- dynamics-nav/uiref/-$-S_11003-Field-Filter-$-.md
This PR fixes 29 missing descriptions.
> [Bulk] Validation: fixed missing descriptions 5/25

- dynamics-nav/DELETE-Function--RecordRef-.md
- dynamics-nav/DELETEALL-Function--RecordRef-.md
- dynamics-nav/DELETEENCRYPTIONKEY.md
- dynamics-nav/DELETELINK-Function--Record-.md
- dynamics-nav/DELETELINK-Function--RecordRef-.md
- dynamics-nav/DELETELINKS-Function--Record-.md
- dynamics-nav/DELETELINKS-Function--RecordRef-.md
- dynamics-nav/DELSTR-Function--Code--Text-.md
- dynamics-nav/Delete-Operation.md
- dynamics-nav/DeleteAllowed-Property.md
- dynamics-nav/DeleteObjects.md
- dynamics-nav/Demo-Option.md
- dynamics-nav/Deploying-Microsoft-Dynamics-NAV-Using-ClickOnce.md
- dynamics-nav/Deploying-Microsoft-Dynamics-NAV-Using-the-Example-Scripts.md
- dynamics-nav/Deploying-Microsoft-Dynamics-NAV-on-Cloud-Services-Other-Than-Microsoft-Azure.md
- dynamics-nav/Deploying-Microsoft-Dynamics-NAV-on-One-Virtual-Machine-Using-Example-1VM-Script.md
- dynamics-nav/Deploying-Microsoft-Dynamics-NAV-on-Two-Virtual-Machines-Using-Example-2VM-Script.md
- dynamics-nav/Deploying-the-Microsoft-Dynamics-NAV-Web-Server-Components-2017.md
- dynamics-nav/Deploying-the-Microsoft-Dynamics-NAV-Web-Server-Components-in-a-Demonstration-Environment.md
- dynamics-nav/Deploying-the-Microsoft-Dynamics-NAV-Web-Server-Components-in-a-Single-Computer-Environment.md
- dynamics-nav/Deploying-the-Microsoft-Dynamics-NAV-Web-Server-Components-in-a-Three-Computer-Environment.md
- dynamics-nav/Deploying-the-Microsoft-Dynamics-NAV-Web-Server-Components-in-a-Two-Computer-Environment.md
- dynamics-nav/Deployment.md
- dynamics-nav/Description-Property.md
- dynamics-nav/Designing-Application-Objects.md
- dynamics-nav/Designing-MenuSuites.md
- dynamics-nav/Designing-RDLC-Report-Layouts.md
- dynamics-nav/Designing-Reports.md
- dynamics-nav/Designing-for-Different-Screen-Sizes-on-Tablet-and-Phone.md
- dynamics-nav/deletearchivedata-function.md
> [Bulk] Validation: validation fixes JM 5/25c

- dynamics-nav/ABS-Function--Decimal--Integer--BigInteger-.md
- dynamics-nav/ACTIVATE-Function--Debugger-.md
- dynamics-nav/ACTIVATE-Function--TestPage-Field-.md
- dynamics-nav/ACTIVE-Function--FieldRef-.md
- dynamics-nav/ACTIVE-Function--KeyRef-.md
- dynamics-nav/ADCS-Overview.md
- dynamics-nav/ADDFIELD-Function.md
- dynamics-nav/ADDFIELDNO-Function.md
- dynamics-nav/ADDLINK-Function--Record-.md
- dynamics-nav/ADDLINK-Function--RecordRef-.md
- dynamics-nav/ADDRECORD-Function.md
- dynamics-nav/ADDRECORDREF-Function.md
- dynamics-nav/ADDTABLE-Function.md
- dynamics-nav/ADDTEXT-Function--BigText-.md
- dynamics-nav/About-Permissions.md
- dynamics-nav/AccessByPermission-Property.md
- dynamics-nav/Accessibility-Features-of-Microsoft-Dynamics-NAV-Windows-Client.md
- dynamics-nav/Accessibility.md
- dynamics-nav/Accessing-Columns-of-a-Query-Dataset.md
- dynamics-nav/Accessing-Objects-in-Other-Databases-or-on-Linked-Servers.md
- dynamics-nav/Action-Icon-Library.md
- dynamics-nav/Actions-Overview.md
- dynamics-nav/Activating-the-Debugger.md
- dynamics-nav/Adding-Actions-to-Pages.md
- dynamics-nav/Adding-Help-to-the-Microsoft-Dynamics-NAV-Universal-App.md
- dynamics-nav/Adding-Languages-to-Microsoft-Dynamics-NAV.md
- dynamics-nav/Adding-a-FactBox-to-Page.md
- dynamics-nav/Additional-Components.md
- dynamics-nav/Administration-of-Microsoft-Dynamics-NAV-on-Microsoft-Azure.md
- dynamics-nav/Altering-Databases---Advanced-Tab.md
> [Bulk] Validation: validation fixes JM 5/24b

- README.md
- articles/dynamics-current-limits.md
- articles/dynamics-open-api.md
- articles/dynamics-rate-limits.md
- articles/dynamics_error_codes.md
- dynamics-nav/How-to--Create-a-Microsoft-Azure-Virtual-Machine-Operating-System-Image-for-Microsoft-Dynamics-NAV.md
- dynamics-nav/help-and-support.md
**Global effort to fix build validation errors**
The Microsoft Skilling team is fixing build validation errors and specific brand inconsistencies in Microsoft technical documentation for the rest of FY23 Q1. This will help address various accessibility, security, and usability issues. This PR was generated using DocuTune. It includes only targeted fixes and minor formatting adjustments.
DocuTune PRs improve quality of technical content by finding and automatically correcting a broad set of issues only where the correction is suitable. Please review within five business days and merge or comment in the PR with any changes you'd like to see. Thank you!
CorrelationId: 0df9c2d6-63f8-4d1e-8b57-b33611a06514
InitiativeId: docutune-build-validation-issues-2022-05
PointOfContact: Alex Buck
> [BULK UPDATE] DocuTune - Fix build validation issues: docs-link-absolute

- README.md
- dynamics-nav/Binding-a-Windows-Client-Control-Add-in-to-the-Database.md
- dynamics-nav/C-AL-Repetitive-Statements.md
- dynamics-nav/How-to--Create-a-Windows-Client-Control-Add-in.md
- dynamics-nav/Upgrading-the-Data.md
- dynamics-nav/index.md
**Global effort for the Microsoft Learn platform rebrand**
The Microsoft team is applying changes to content for the Microsoft Learn platform rebrand. Changes include modifications to current Microsoft Learn and Microsoft Docs terminology as well as associated domain name and content URL path changes.
Please review this draft PR and provide any necessary comments as soon as possible. Because these fixes are tightly scoped, we have approval to automatically merge these changes to the default branch for publication.
This PR was generated via DocuTune. It includes only targeted fixes and minor formatting adjustments.
CorrelationId: d8c4c3ac-d49a-4c95-9ddc-9822ca297907
InitiativeId: docutune-rebranding-2022-09
PointOfContact: Alex Buck
> [BULK UPDATE] DocuTune - Rebranding

- dynamics-nav/SETAUTOCALCFIELDS-Function--Record-.md
Improved quality of the code in Example 1
> Updated Example 1 code

- dynamics-nav/Deploying-the-Microsoft-Dynamics-NAV-Web-Server-Components.md
- dynamics-nav/Deployment-Scenarios-for-the-Microsoft-Dynamics-NAV-Web-Server-Components.md
- dynamics-nav/How-to--Install-the-Web-Server-Components.md
[defect 398066](https://dynamicssmb2.visualstudio.com/Dynamics%20SMB/_workitems/edit/398066):
[Deploy the Web Server Components - Dynamics NAV | Microsoft Docs](https://review.learn.microsoft.com/en-us/dynamics-nav/deploying-the-microsoft-dynamics-nav-web-server-components?branch=defect398066-mobile-app#network-topology)
[Web Server Components Deployment Scenarios - Dynamics NAV | Microsoft Docs](https://review.learn.microsoft.com/en-us/dynamics-nav/deployment-scenarios-for-the-microsoft-dynamics-nav-web-server-components?branch=defect398066-mobile-app#deployment-scenarios)
[How to: Install the Web Server Components - Dynamics NAV | Microsoft Docs](https://review.learn.microsoft.com/en-us/dynamics-nav/how-to--install-the-web-server-components?branch=defect398066-mobile-app)
> Defect398066 mobile app
